name: Ticket Tracker

on:
  schedule:
    - cron: '*/3 * * * *'  # Runs every 3 minutes
  workflow_dispatch:

concurrency:
  group: ticket-tracker
  cancel-in-progress: true
  
jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install deps
        run: npm install

      - name: Run script
        env:
          MODAL_URL: ${{ secrets.MODAL_URL }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: node ticket-tracker.js
